### ISSUE TITLE
TXT files

### ISSUE THREAD

**Issue by RedGuy12** [EmmanuelBeziat/vscode-great-icons#191]
## Format to support

* [txt](https://en.wikipedia.org/wiki/Text_file)
* Official icon (lhttps://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Text-txt.svg/64px-Text-txt.svg.png)
* .txt

**Comment by EmmanuelBeziat** [comment]
Hi,

Thanks for your suggestion and sorry for the long delay. This is added in the new 2.1.65 version, live now!

**Comment by RedGuy12** [comment]
thanks, but i don't see it...

**Comment by EmmanuelBeziat** [comment]
Oops, my silly mistake. It's okay in 2.1.66, check it out ;)

**Comment by geekley** [comment]
I hate to "complain" about this kind of thing, but I have to say... I honestly didn't like this update...
Although the icon itself does look really nice, there's practical reasons for why I saw it as a downgrade:

1. It feels really out-of-place among the rest of the icons. Some of the other icons (such as json, yaml, markdown, and language icons like C# and JS) are very "symbolic" (basic color + simple symbol). The txt icon, however, despite being the simplest of file types, has a more complex icon. This feels kinda wrong, because it draws too much attention in relation to the other icons, which are almost always more important in the project than txt files.
2. If you really have to stick with the notepad metaphor, at least remove the pencil. The pencil on the notepad makes it seem like it's more an app icon than a file-type icon. The file-type is just the text itself, not the ability to write on it.

If you allow me to suggest an improvement, IMHO, a better icon would be something more like this:
- (optional) Simple square (just outline, no fill), maybe with very slight round edges if appropriate
    - If you have to maintain the notepad metaphor, you can keep the vertical strokes above the square for the spring, but I think it's not even necessary. In any case please make the square have no fill (fully transparent) if you use it, so it won't draw more attention than the other icons.
- Simple horizontal lines indicating text; at least 2 full lines + last line partially completed
- Keep the white-grayish color; I'd use no more than 1 or 2 grayscale colors
- Remove the pencil

---
I've decided to try to make these changes on my own, and I think it already looks a lot better:
![Screenshot of current txt icon](https://user-images.githubusercontent.com/38332912/119592029-13dad600-bdae-11eb-98bb-806cf337a8df.png) ![Screenshot of suggested txt icon](https://user-images.githubusercontent.com/38332912/119591844-b8104d00-bdad-11eb-9acb-73508e929f0f.png) ![Screenshot of suggested txt icon in light theme](https://user-images.githubusercontent.com/38332912/119592387-c57a0700-bdae-11eb-8ce4-c647ad400000.png) ![Suggested txt icon](https://user-images.githubusercontent.com/38332912/119592213-6a481480-bdae-11eb-9b22-6762d728b63e.png)

If you want to include something like this in the theme, feel free to use it without attribution. It's a really simple SVG:
```svg
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 16 16" width="16" height="16" id="txt-icon">
  <path id="spring"
    d="m 3.5,1.5 v 0.75 z m 2.25,0 v 0.75 z m 2.25,0 v 0.75 z m 2.25,0 v 0.75 z m 2.25,0 v 0.75 z"
    style="fill:none;stroke:#95a5a6;stroke-width:1.5;stroke-linejoin:round" />
  <rect id="paper" x="1.5" y="2.5" width="13" height="12" rx="1.25" ry="1.25"
    style="fill:none;stroke:#bdc3c7;stroke-width:1" />
  <path id="lines"
    d="m 4.25,5.5 h 7.5 m -7.5,2 h 7.5 m -7.5,2 h 7.5 m -7.5,2 h 3.75"
    style="fill:none;stroke:#95a5a6;stroke-width:1;stroke-linecap:round" />
</svg>
```

**Comment by EmmanuelBeziat** [comment]
Hi @geekley 

Thanks for sharing your thoughts about it. The icon you proposed looks cool, I'll add it to the next version of the pack soon.
Stay tuned!

**Comment by EmmanuelBeziat** [comment]
@geekley it's done! Check the new 2.1.76 version!

Thanks for helping improving the pack!

**Comment by geekley** [comment]
Ah nice to know that you liked it!
Though I think I should've made it slightly darker, now that I noticed, the contrast seems kinda low in light theme.
Well, whatever, I don't care about light theme anyways :laughing:

**Comment by EmmanuelBeziat** [comment]
> Well, whatever, I don't care about light theme anyways 😆

😇😇😁
