### ISSUE TITLE
another .env format

### ISSUE THREAD

**Issue by gorjiali** [EmmanuelBeziat/vscode-great-icons#200]
## Format to support

* [Type of file](https://github.com/motdotla/dotenv)
* [Official icon](https://raw.githubusercontent.com/motdotla/dotenv/master/dotenv.png)
* Files extensions: .env.*.*

**Comment by EmmanuelBeziat** [comment]
Hi @gorjiali 

Sorry, I didn't get wich file format you wanted to see supported? `.env` already has an icon.

**Comment by gorjiali** [comment]
Hi @EmmanuelBeziat 
for example ```env.dev.local```

![Capture](https://user-images.githubusercontent.com/49091958/109295824-a5d15200-7844-11eb-8c90-065c96459ae7.PNG)

**Comment by EmmanuelBeziat** [comment]
Okay, got it. The problem is that there seems to have no way to use some kind of wildcard to match unspecific extensions… So I'm forced to add them manually.

I’ll add `.env.development.local` and `.env.production.local`, but be aware that if you use any other non-specific filename, it won't work :/ 

Stay tuned, I'll do that in a bit.

**Comment by EmmanuelBeziat** [comment]
Hi,

It's done, check the new v2.1.67!
